name: caller1
on: [push]
jobs:
  caller1:
    runs-on: macos-12
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v3
      - run: echo "Caller 1"
      - uses: hidashun/GitHubActionExp/.github/workflows/callee@main
        with:
          config-path: this/is/config/path
        secrets:
          envPAT: hogehoge