name: callee
on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      envPAT:
        required: true
jobs:
  callee:
    runs-on: macos-12
    timeout-minutes: 3
    steps:
    - run: |
      echo ${{ inputs.config-path }}
      echo ${{ secrets.envPAT }}
