name: caller1
on: [push]
jobs:
  caller1:
    steps:
      - uses: actions/checkout
      - uses: hidashun/GitHubActionExp.git/.github/workflows/callee.yml@other-branch
        with:
          config-path: this/is/config/path
        secrets:
          envPAT: hogehoge